---
title: "About this Website"
---

This website was built with data from the [*clinicaltrials.gov*](https://clinicaltrials.gov/) API to identify studies that included a keyword or condition listing of Aphasia (excluding primary progressive aphasia and other dementias.) 

To add your study to this website you will need to [submit the study](https://clinicaltrials.gov/ct2/manage-recs) to *clinicaltrials.gov*. This has [a number of benefits for the research community and general public](https://clinicaltrials.gov/ct2/manage-recs/background). While submission to *clinicaltrials.gov* is required for funded clinical trials in the US, voluntary submission is also permitted for other studies.

Please contact me if you would like to add the following information to your study:

- Whether or not your study can be completed remotely or long-distance travel costs are reimbursed
- A youtube link to an aphasia-friendly recruiting video to your study's information card (IRB-approved if required).

If there is an error, please [contact me](https://robcavanaugh.com) or [file an issue here]( https://github.com/rbcavanaugh/find-aphasia-research/issues). If you are unable to submit your study at clinicaltrials.gov but would like to add your study to the website, please contact me and let me know why you are unable to submit to clinicaltrials.gov. 

\- Rob

*P.S. I am happy to add a dedicated map page for other world regions if enough studies are submitted. For now, other studies are only included in the "Study Details" page.*

