---
title: "Current Aphasia Research Studies in the US"
description: "1. Click on a green pin. 2. Click on the study name to get more information."
---

```{r setup, include=FALSE}
library(flexdashboard)
library(here)
library(tidyverse)
library(htmltools)

library(RColorBrewer)


clinical_trials = read.csv(here("data", "clinical_trials_clean.csv"))

noise = tibble(
  OrgFullName = unique(clinical_trials$OrgFullName),
  lon_noise = rnorm(length(unique(clinical_trials$OrgFullName)), 1, 0.001),
  lat_noise = rnorm(length(unique(clinical_trials$OrgFullName)), 1, 0.001)
)

data = clinical_trials %>%
  ungroup() %>%
  select(name = BriefTitle, Condition, StartDate, NCTId,
         OrgFullName, BriefSummary, DetailedDescription,
         Keyword, StudyType, EligibilityCriteria, HealthyVolunteers,
         MinimumAge, Gender, LocationCity, LocationState, lon, lat) %>%
  left_join(noise, by = "OrgFullName") %>%
  mutate(name = gsub("[.]", "", x=name),
         z=1,
         link=paste0("https://rbcavanaugh.github.io/find-aphasia-research/list_view.html#",NCTId),
          location = "on site",
          lat = lat*lat_noise,
          lon = lon*lon_noise
        )

library(rsvg)
library(fontawesome)
library(stringr)


fa_to_png_to_datauri <- function(name, ...) {
  
  tmpfl <- tempfile(fileext = ".png")
  
  fontawesome::fa_png(name, file = tmpfl, ...)
  
  knitr::image_uri(tmpfl)
  
}

# specify colors tu resue in the series/tooltips
rcol <- "#006400"

mark_alt <- fa_to_png_to_datauri(name = "map-marker-alt", width = 20 , fill = rcol)


```


```{r, include = F}
library(highcharter)
library(here)
library(tidyverse)


map_plot = 
  hcmap("countries/us/us-all", showInLegend = FALSE) %>%
  hc_add_series(
    data = data[data$location=="on site",], 
    type = "mappoint",
    name = "Study", 
    #color = "#00640050",
     minSize = "2%",
     maxSize = "2%",
    tooltip =list(
      pointFormat = '<a href={point.link}>{point.BriefTitle}</a>'
    ),
    marker = list(radius = 8,
                  symbol=str_glue("url({data_uri})", data_uri = mark_alt)),
     cluster = list(enabled = TRUE,
                    allowOverlap = T,
                    layoutAlgorithm = list(type = "kmeans",
                                           distance="2%"))
  ) %>%
  hc_tooltip(
      style = list(pointerEvents ='auto'),
      headerFormat = '',
      formatter = JS("function() {
        if (this.point.clusteredData) {
          let clusterPointsAmount = this.point.clusterPointsAmount,
            clusterNameAll = [];
          this.point.clusteredData.forEach(p => {
            clusterNameAll.push(
        '<br>' +
        '<a href=' + p.options.link + '>' + p.options.name + '</a><br>' +
        '- <a href=' + p.options.link + '>' + p.options.OrgFullName + '</a><br>'
        );
          })
          return clusterNameAll;
        }
        return '<a href='+ this.point.link + '>' + this.point.name + '</a><br>' +
                '- <a href='+ this.point.link + '>' + this.point.OrgFullName + '</a><br>';
      }")
  ) %>%
   hc_mapNavigation(enabled = TRUE) %>%
  hc_plotOptions(
    series=list(stickyTracking=F,
                            dataLabels = list(enabled = F)
                             )) %>%
  hc_add_dependency("modules/marker-clusters.js")

# <span style="color:{series.color}; font-family: FontAwesome">{series.options.icon}</span>
# hc_add_series(
#     data = data[data$location=="online",], 
#     type = "mapbubble",
#     name = "Online Study", 
#     # minSize = "2%",
#     # maxSize = "2%",
#     color = hex_to_rgba("darkblue", alpha = 0.3),
#     tooltip =list(
#       pointFormat = "<a href='{point.link}'>{point.BriefTitle}</a>"
#     ),
#     marker = list(fillOpacity=0.3)
# ) %>%

```

    
```{r, echo = F, layout = "l-page", fig.height=6}
map_plot
```
   

